const express = require('express')
const router = express.Router()
    //controlles
const { AddPhoto } = require('../../Controlles/Company/AddPhoto')
const { AddAbout } = require('../../Controlles/Company/ProfileInfo')
const { AddVision } = require('../../Controlles/Company/ProfileInfo')
const { AddMission } = require('../../Controlles/Company/ProfileInfo')
const { AddWorkes } = require('../../Controlles/Company/ProfileInfo')
const { RemoveWorkes } = require('../../Controlles/Company/ProfileInfo')
const { UpdateProfile } = require('../../Controlles/Company/ProfileInfo')
const { DeleteFollower } = require('../../Controlles/Company/Followee')
const { Follower } = require('../../Controlles/Company/Followee')
const { Followers } = require('../../Controlles/Company/Followee')
    //routes
router.post('/changePhoto', AddPhoto)
router.post('/about', AddAbout)
router.post('/vision', AddVision)
router.post('/vision', AddVision)
router.post('/mission', AddMission)
router.post('/addWorkes', AddWorkes)
router.post('/removeWorkes', RemoveWorkes)
router.post('/updateProfile', UpdateProfile)
router.post('/follower', Followers)
router.post('/follower/:userId', Follower)
router.post('/deleteFolower', DeleteFollower)
module.exports = router