export const TranslationAm ={
    Login:'ይግቡ',
    Signup:"ይመዝገቡ",
    ForgetPassword:'የይለፍ ቃል ረስተዋል',
    CreateAccount:'አዲስ መለያ ይፍጠሩ',
    Language:'ቆንቆ',
    Email:'ኢሜይል',
    Password:'የይለፍ ቃል',
    ConfirmPassword:'የይለፍ ቃል ያረጋግጡ',
    FirstName:'የእርሶ ስም',
    LastName:"የአባት ስም",
    Country:"ሀገር",
    City:'ከተማ',
    Phone:'ስልክ',
    OrganizationName:'የድርጅት ስም',
    industry:'ኢንዱስትሪይ',
    OrganizationSize:'የሰራተኝ መጠን',
    OrganizationType:'የድርጅቶ አይነት',
    Tagline:'ስለ ድርጅቶ',
    ResetPassword:'የይለፍ ቃል ያስመልሱ',
    enterEmail:"የኢሜይል አድራሻዎን ያስገቡ",
    Next:'ቀጣይ',
    Back:'ተመለስ',
    VerifyEmail:'የኢሜይል ማረጋገጫ',
    EnterCode:'እባክዎ ወደ ኢሜይልዎ የተላከውን ኮድ ያስገቡ',
    Code:'ኮድ',
    Verify:'አረጋግጥ',
    DidntReceiveCode:"ኮድ አልተቀበለም",
    ResendCode:'ድጋሚ ላክ',
    NewPassword:'አዲስ የይለፍ ቃል',
    PersonalAccount:'የግል ገጽ',
    CompanyPage:'የድርጅት ገጽ',
    Home:"መነሻ ገጽ",
    Message:"መልእክት",
    Network:"ጎደኝች",
    Notification:"አዲስ",
    Profile:"መለያ",
    SettingAndPrivacy:'ቅንብሮች እና ግላዊነት',
    LogOut:"ዘግተው ይውጡ",
    General:'ግላዊነት',
    Security:'ደሕንነት',
    Name:'ስም',
    Location:'መገኛ',
    FNameRequired:'የእርሶ ስም ያስፈልጋል',
    LNameRequired:'የአባት ስም ያስፈልጋል',
    CountryNameRequired:'የሚኖሩብርት ሀገር ስም ያስፈልጋል',
    CityNameRequired:'የሚኖሩበት ከተማ ስም ያስፈልጋል',
    institution:'የተምህርት ተቆም',
    fieldOfStudy:'የተማሩት ትምህርት',
    WorkAt:'የስራ ቦታ',
    Postion:'የስራ ክፍል',
    save:'ቀይር',
    OldPassword:'የይለፍ ቃሎን ያስገቡ',
    ChangePassword:'የይለፍ ቃል ይቀይሩ',
    IncorectOldPassword:'ያስገቡት የ ይለፍ ቃል የተሳሳተ ነው',
    ChangingPasswordFailde:'የይለፍ ቃል መቀየር አልተሳካም',
    PasswordChanged:'የይለፍ ቃል  በተሳካ ሁኔታ ተቀይሮል',
    PleaseEnterOldPassword:'የይለፍ ቃል ማስገባት አለቦት',
    PleaseEnterNewPassword:'አዲስ የይለፍ ቃል ማስገባት አለቦት',
    PleaseConfrimNewPassword:'አዲስ የይለፍ ቃል ማረጋገጫ ማስገባት አለቦት',
    PleaseEnterPassword:'የይለፍ ቃል ማስገባት አልቦት',
    ConfrimPassworNotMatch:'አዲስ የይለፍ ቃል ማረጋገጫ ልክ አይደለም',
    Work:'ስራ',
    DeleteAccount:'መለያ መሰረዝ',
    AccontDeltionFailed:'መለያ መስረዝ አልተሳካም እንደገና ይሞክሩ',
    AgreeToDeleteAccount:'መለያዎን ለመደለት እርግጠኛ ኖት',
    location:'መኖሪያ',
    StudiedAt:'የተማሩበት ተቆም',
    GraduteOf:'የተማሩት ትምህርት',
    startedDate:'ትምህርቱን የጀመሩበት አመት',
    endDate:'ትምህርቱን ያጠናቀቁበት አመት',
    Grade:'የትምህርቶ ውጤት',
    InstitionRequired:'የተማሩበት ተቆም ያስፈልጋል',
    fildeOfStudyRequired:'የተማሩት ትምህርት ያስፈልጋል',
    startedDateRequired:'ትምህርቱን የጀመሩብርት ቀን ያስፈልጋል',
    endDateRequired:'ትምህርቱን ያጠናቀቁበት ቀን ያስፈልጋል',
    GradeRequired:'የትምህርት ውጤቶ  ያስፈልጋል',
    Education:'ትምህርት',
    job:'ስራ',
    yearOfStudy:'የተማሩበት አመት',
    uploadPhoto:'ፎቶ ይምረጡ',
    changePhoto:'ፎቶ ይቀይሩ',
    photoUploadFaild:'ፎቶ መቀየር አልተሳካም',
    Cancel:'ተመለስ',
    ProfilePhotoDialogTitle:" ምንም ዓይነት ሙያዊ ፎቶግራፍ አያስፈልግም! እርሶን የሚወክል ነገር ብቻ ይሁን ",
    ProfilePhotoDialogText:' አባላት እውነተኛ ማንነታቸውን የሚገልጽ ፎቶ እንዲጠቀሙ እንመክራላን፣ የእራስዎን ፎቶ እንዲጭኑ እናሳስባለን',
    title:'የስራ ልምዶ',
    employmentType:'የስሩት የስራ  ሰአት',
    companyName:'የመስራቤት ስም',
    AddEducation:"ትምህርት ያስገቡ",
    AddExperience:"የስራ ልምድ ያስገቡ",
    AddSkill:'ችሎታ ያስገቡ',
    skill:"ችሎታ",
    Experience:'የስራ ልምድ',
    workedAs:'የስራ አይነት',
    Workedat:'የመስራቤት ስም',
    workType:'የስራ ሰአት',
    yearOfExprience:'የስራ ልምድ ጊዜ',
    PassedSkillAssissment:'የ BOSNP ችሎታ ማረጋገጫ ፈተና አልፎል',
    DemonestrateSkill:'ችሎታዎን ያረጋግጡ',
    ExprienceTitileRequired:'የስራ ልምድ ያስፈልጋል',
    SelectEmployementType:'የስሩት የስራ  ሰአት ይምረጡ',
    companyNameRequired:'የመስራቤት ስም ያስፈልጋል',
    skillRequired:'ችሎታ ያስፈልጋል',
    SkillNotAdd:'ችሎታ ማስገባት አልተሳካም',
    ExprienceinNotAdd:'የስራ ልምድ ማስገባት አልተሳካም',
    ExpriencestartedDateRequired:'ስራ የጀመሩብርት ቀን ያስፈልጋል',
    ExprienceendDateRequired:'ስራ ያጠናቀቁበት ቀን ያስፈልጋል',
    FullTime:'ሙሉ ቀን',
    PartTime:'ክፍል ሰዓት',
    SelfEmployed:'የራስን ሥራ',
    Freelance:'ፍሪሊያንስ',
    Contract:'የውል',
    Intership:'ኢንተርነት',
    Apprenticeship:'የሙያ ሥልጠና',
    Seasonal:'ወቅታዊ',
    EditExperience:'የስራ ልምድ ያስተካክሉ',
    Delete:'ሰርዝ',
    DeleteSkill:'ችሎታ መሰረዝ',
    skillDeleteWarning:'የህንን ችሎታ ለመሰረዝ እርግጠኛ ኖት',
    Yes:'አዎ',
    Dashboard:"መርጃዎች",
    PersonalAccounts:'የግለሰብ ገጾች',
    CompanyPages:'የድርጅት ገጾች',
    JobVacancies:'የስራ ማስታወቂያዎች',
    Post:'ተለጣፊዎች',
    Events:'ሁነቶች',
    Reports:'ቅሬታዎች',
    SkillAssessment:'የችሎታ ፈተናዎች',
    AddAdmin:'ተቆጣጣሪ ማስገባት',
    NewProgram:'አዲስ ትምህርት አይነት',
    ExstingProgram:'ለነባር የትምህርት አይነት',
    NewAssessment:'ለአዲስ የትምህርት አይነት',
    Program:'የትምህርት አይነት',
    Content:'ማብራሪያ',
    DescribeTheContent:'የፈተናውን ጥያቄ ያብራሩ',
    ProgramTypeRequired:'የትምህርት አይነት ያስፈልጋል',
    DescriptionRequired:'የጥያቄ ማብራሪያ ያስፈልጋል',
    ProgramAlreadyExsists:'ይሄ የትምህርት አይነት ጥያቂዎች ተሰርተውለታል ጥያቄ ለማስገባት ይሄን ይጫኑ',
    For:'ለ',
    Question:'ጥያቄ',
    OptionOne:'አንደኝ ምርጫ',
    OptionTwo:'ሁለተኛ ምርጫ',
    OptionThree:'ሶስተኛ ምርጫ',
    OptionFour:'አራተኛ ምርጫ',
    Add:'አስገባ',
    Clear:'አጥፋ',
    Answer:'መልስ',
    unableToaddQuestions:'ጥያቄዎቹ አልገቡም እባኮን ከ እንድደገና የሞክሩ',
    AddQeutionAssessment:'ጥያቄ ማስገባት',
    EditAssessment:'ፈተና ማስተካከል',
    PasswordRequired:'አዲስ የይለፍ ቃል ያስፈልጋል',
    EmailRequired:'የኢሜል አድራሻዎ ያስፈልጋል',
    InvalidCode:'የተሳሳተ ሚስጥር ቁጥር',
    InvalidOtp:'የተሳሳተ ቁጥር እንደገና ዪሞክሩ',
    maxAttempts:'የተሳሳተ ቁጥር ከሶስት ጊዜ በላይ አስገብተዋል አዲስ ሚስጥር ቁጥር ይዘዙ',
    userVerificatinFaild:'የኢሜል አድራሻዎ ማረጋግጥ አልተቻለም እንደገና ይሞክሩ',
    codeExpired:'የኢሜል አድራሻዎ ማረጋገጫ ጊዜ አልፎል አዲስ ሚስጥር ቁጥር ይዘዙ',
    notSignUp:'መለያ አልከፈቱም',
    useNotFound:'መለያ አልተገኝም',
    ChangePasswordFaild:'የሚስጥር ቁጥር መቀየር አልተሳካም',
    codeSendigFaild:'የኢሜል አድራሻዎ ማረጋገጫ መላክ አልተሳካም',
    InvalidEmail:'የተሳሳተ ኢሜል አድራሻ',
    PhoneNumberRequired:'ያስልክ አድራሻ ያስፈልጋል',
    OrganizationNameRequierd:'የድርጅቶ ስም ያስፈልጋል',
    industryRequierd:'የሚሰሩንት ዘርፍ ያስፈልጋል',
    OrganizationSizeRequierd:'የድርጅቶ ስፋት ያስፈልጋል',
    OrganizationTypeRequierd:'የድርግጅቶ አይነት ያስፈልጋል',
    EditQeustion:'ጥያቄዎች ማስተካከል',
    AddQuestion:'አዲስ ጥያቄ',
    Skillassessments:'የችሎታ ማረጋገጫ',
    checkSkills:"የBOSNP የችሎታ ማረጋገጫ ያግኙ",
    topics:'እርእስ',
    SearchTopic:'እርእስ ይፈልጉ...',
    ChangeTopics:'እርእስ ይቀይሩ',
    instruction1:'5 የምርጫ ጥያቄዎች መመለስ ያኖርቦታል',
    instruction2:'ለእያንዳዱ ጥያቄ 1 30 ሰከንድ ያሎት',
    instruction3:'50% እና ከዛ በላይ ማምጣት አለብቦት የBOSNP ማረጋገጫ ለማግኘት',
    instruction4:'ፈተናውን በአንድ ክፍለ ጊዜ ነው መጨርስ ያሎቦት',
    instruction5:'ከወደቁ ፈተናውን ድጋሚ መውሰድ ይችላሉ',
    instruction6:'የፈተናውን ውጤት ለማንም አናሳይም',
    beforeStart:'ፈተናውን ከመጀመሮ በፊት',
    Assessment:'ግምገማ',
    Start:'ጀምር',
    tryAgain:'እንደገና ይሞክሩ',
    BackToProfile:'ወደ መለያ ይመለሱ',
    viweResult:'ውጤት',
    didntEarnBadge:'ፈተናውን ማለፍ አልቻሉም',
    youEarnBadge:'ፈተናውን አልፈዋል የBOSNP  ',
    badge:'ማረጋገጫ አግተዋል',
    Congratulations:"እንኮን ደስ ያሎት",
    timeExpired:"ሰዐት አልቆል",
    newQuestionAdd:'አዲስ ጥያቄ ገብቶል',
    newQuestionNotAdd:'አዲስ ጥያቄ አልገባም',
    QuestionDeleted:'ጥያቄ ተሰርዞል',
    unableToDeleteQuestion:'ጥያቄ መሰርዝ አልተሳካም',
    DeleteAssessment:'ፈተና መሰረዝ',
    ConfirmDeleteAssessment:'ፈተና መሰረዝ ያረጋግጡ',
    assessmentDeleted:'ፈተና ተሰርዞል',
    unableToDeleteAssessment:'ፈተና አልተሰረዘም',
    DeleteQuestion:'ጥያቄ መሰረዝ',
    ConfirmDeleteQuastion:'ጥያቄ መሰረዝ ያረጋግጡ',
    DescriptionChanged:'ማብራሪያ ተቀይሮል',
    unableToUpdateDescription:'ማብራሪያ አልተቀየረም',
    taglineDescription:'ይህን መዝገብ ድርጅቶ ምን እንደሚሰራ ያብራሩበት መለያውን ከከፈቱ ቦሃላ መለያ ውስጥ በመጋብት መቀየር ይችላሉ'
}
export const TranslationEn ={
    Login:"Login",
    Signup:"Signup",
    ForgetPassword:'Forgot password',
    CreateAccount:'Create Account',
    Language:'Language',
    Email:'Email',
    Password:'Password',
    ConfirmPassword:'Confirm Password',
    FirstName:'First Name',
    LastName:"Last Name",
    Country:"Country",
    City:'City',
    Phone:'Phone Number',
    OrganizationName:'Name',
    industry:'Industry',
    OrganizationSize:'Organization size',
    OrganizationType:'Organization type',
    Tagline:'Tagline',
    ResetPassword:'Reset your password',
    enterEmail:"enter your email address",
    Next:'Next',
    Back:'Back',
    VerifyEmail:'Verify Email',
    EnterCode:'Please enter the code sent to your email',
    Code:'Code',
    Verify:'Verify',
    DidntReceiveCode:"Didn't receive code",
    ResendCode:'Resend Code',
    NewPassword:'New Password',
    PersonalAccount:'Personal Account',
    CompanyPage:'Company Page',
    Home:"Home",
    Message:"Message",
    Network:"My Network",
    Notification:"Notification",
    Profile:"Profile",
    SettingAndPrivacy:'Setting and Perivacy',
    LogOut:"Log Out",
    General:'General',
    Security:'Security',
    Name:'Name',
    Location:'Location',
    FNameRequired:'First Name Requierd',
    LNameRequired:'Last Name Requierd',
    CountryNameRequired:'Country Name is Requierd',
    CityNameRequired:'City Name is Requierd',
    institution:'Institution',
    fieldOfStudy:'Field of Study',
    WorkAt:'Work At',
    Postion:'Postion',
    save:'Save',
    OldPassword:'Old Password',
    ChangePassword:'Change Password',
    IncorectOldPassword:'Incorrect Old Password',
    PasswordChanged:'Password Changed Succfully',
    ChangingPasswordFailde:'Changing Password Failde',
    PleaseEnterOldPassword:'Old password requierd',
    PleaseEnterNewPassword:'New password requierd',
    PleaseConfrimNewPassword:'Confirm password requierd',
    PleaseEnterPassword:'Please Enter Your Password',
    ConfrimPassworNotMatch:'Confrim password does not match',
    Work:'Work',
    DeleteAccount:'Delete Account',
    AccontDeltionFailed:'Account deletion failde try again',
    AgreeToDeleteAccount:'Are you sure to delete your account',
    location:'Lives in',
    StudiedAt:'Studied at',
    GraduteOf:'Gradute of',
    startedDate:'Started year',
    endDate:'End year',
    Grade:'Grade',
    InstitionRequired:'Instition required',
    fildeOfStudyRequired:'Filde of study required',
    startedDateRequired:'started date required',
    endDateRequired:'end date required',
    GradeRequired:'Grade required',
    Education:'Education',
    job:'Job',
    yearOfStudy:'Year of study',
    uploadPhoto:'Upload Photo',
    changePhoto:'Change photo',
    photoUploadFaild:'Photo upload faild',
    Cancel:'Cancel',
    ProfilePhotoDialogTitle:" No professional headshot needed! Just something that represents you",
    ProfilePhotoDialogText:' we suggest members to use their real identities,upload a photo of yourself',
    title:'Title',
    employmentType:'Employment Type',
    companyName:'Company Name',
    AddEducation:"Add Education",
    AddExperience:"Add Exprience",
    AddSkill:'Add Skill',
    skill:"Skill",
    Exprience:'Experience',
    workedAs:'Worked as',
    Workedat:'Worked at',
    workType:'Worked type',
    yearOfExprience:'Years of exprience',
    PassedSkillAssissment:'Passed BOSNP skill assessment',
    DemonestrateSkill:'Demostrate skill',
    ExprienceTitileRequired:'Titile required',
    SelectEmployementType:'Select employement type',
    companyNameRequired:'Company name required',
    skillRequired:'Skill required',
    SkillNotAdd:'Skill not add',
    ExprienceinNotAdd:'Exprience not add',
    ExpriencestartedDateRequired:'Started date required',
    ExprienceendDateRequired:'End date required',
    FullTime:'Full-Time',
    PartTime:'Part-Time',
    SelfEmployed:'Self-Employed',
    Freelance:'Freelance',
    Contract:'Contract',
    Intership:'Intership',
    Apprenticeship:'Apperenticeship',
    Seasonal:'Seasonal',
    EditExperience:'Edit Experience',
    Delete:'Delete',
    DeleteSkill:'Delete skill',
    skillDeleteWarning:'Are you sure you want to delete this skill',
    Yes:'Yes',
    Dashboard:"Dashboard",
    PersonalAccounts:'Personal accounts',
    CompanyPages:'Company pages',
    JobVacancies:'Job vacancies',
    Posts:'Posts',
    Events:'Eventes',
    Reports:'Reports',
    SkillAssessment:'Skill assesment',
    AddAdmin:'Add admin',
    NewProgram:'New program',
    ExstingProgram:'Exsting programs',
    NewAssessment:'New assesment',
    Program:'Program',
    Content:'Content',
    DescribeTheContent:'Describe the content',
    ProgramTypeRequired:'Program type required',
    DescriptionRequired:'Description required',
    ProgramAlreadyExsists:'This program already exsists click here to add question',
    For:'For',
    Question:'Question',
    OptionOne:'Option one',
    OptionTwo:'Option Two',
    OptionThree:'Option Three',
    OptionFour:'Option Four',
    Add:'Add',
    Clear:'Clear',
    Answer:'Answer',
    unableToaddQuestions:'Question not add try again',
    AddQeutionAssessment:'Add qeustion',
    EditAssessment:'Edit assessment',
    PasswordRequired:'Password is required',
    EmailRequired:'Email is required',
    InvalidCode:'Invalid code',
    InvalidOtp:'Invalid code please try again',
    maxAttempts:'You have exceeded the maximum number of attempts. Please request a new code.',
    userVerificatinFaild:'user verification failde , try again',
    codeExpired:'Code has expired. Please request a new code',
    notSignUp:'You have not signed up yet',
    useNotFound:'User not found.',
    ChangePasswordFaild:'Changing password failed',
    codeSendigFaild:'Could not send code try again',
    InvalidEmail:'Invalid email',
    PhoneNumberRequired:'Phone number required',
    OrganizationNameRequierd:'Organization name required',
    industryRequierd:'Industry name required',
    OrganizationSizeRequierd:'Organization size required',
    OrganizationTypeRequierd:'Organization type required',
    EditQeustion:'Edit Question',
    AddQuestion:'Add question',
    Skillassessments:'Skill assessments',
    checkSkills:"Check your skill level. Answer 15 multiple choice questions, score 50%, and earn a skill badge.",
    topics:'Topics',
    SearchTopic:'Search topics...',
    ChangeTopics:'Change Topics',
    instruction1:'5 multiple choice questions',
    instruction2:'1 minutes per question',
    instruction3:'Score 50% and above to earn a badge',
    instruction4:'You must complete this assessment in one session to earn badge ',
    instruction5:'You can retake this assessment once if you do not earn a badge',
    instruction6:'We wont show your result to anyone',
    beforeStart:'Before you start',
    Assessment:'Assessment',
    Start:'Start',
    tryAgain:'Try again',
    BackToProfile:'Back to profile',
    viweResult:'Resalt',
    didntEarnBadge:'Unfortunately you did not earn a badge try again',
    youEarnBadge:'You earn BOSBN',
    badge:'badge',
    Congratulations:"Congratulations",
    timeExpired:"Time Expired",
    newQuestionAdd:'New question added',
    newQuestionNotAdd:'Unable to add new question',
    QuestionDeleted:'Question deleted',
    unableToDeleteQuestion:'Unable to delete question try again',
    DeleteAssessment:'Delete Assessment',
    ConfirmDeleteAssessment:'Confirm Delete Assessment',
    assessmentDeleted:'Assessment Deleted',
    unableToDeleteAssessment:'unable To Delete Assessment',
    DeleteQuestion:'Delete question',
    ConfirmDeleteQuastion:'Confirm delete question',
    DescriptionChanged:'Description changed',
    unableToUpdateDescription:'Unable to update description',
    taglineDescription:'Use your tagline to briefly describe what your organization does. This can be changed later.',
    Invitations:"Intvitations",
    PeopleYouMayKnow:'People you may know',
    Connect:'Connect',
    pending:'Pending',
    seeMore:'See more',
    GraduateOf:'Graduate of',
    WorksAt:'Works at',
    InvitationSent:'Invitation sent',
    InvitationNotSent:'Invitation not sent',
    InvitationCancled:'Invitation cancled',
    InvitationNotCancled:'Invitation not cancled',
    Noinvitations:'No pending invitations',
    Accept:'Accept',
    InvitationNotAccepted:'Invitation not accepted',
    InvitationAccepted:"Invitation Accepted",
    Ignore:'Decline',
    RejectedInvitation:'Invitation decline',
    InvitationNotRejected:'Invitation not decline',
    YouAreKnowFriends:'You are know connected with',
    YouHaveDclined:'You have dclined',
    PendingRequest:"Pending requests",
    Connection:'Connections',
    Pages:'Pages',
    StartPost:'Start post',
    WhatToPost:'What do you want to talk about',
    SelectChat:'Select chat to start a message',
    Messaging:'Messaging',
    YourConnection:'Your connections',
    NoPendingRequest:'No pending request',
    Search:'Search......',
    MakeFriends:'Send invitation to meet new friends',
    MakeFriendsToChat:'Connect with peopels to send messages',
    About:"About",
    Vision:'Vision',
    Mession:'Mission',
    Workes:"Workes",
    Partners:"Partners",
    AboutCompany:'Describe what your company do this will help you to get more followers',
    MissionCompany:'Describe mission of your company to your followers',
    VisionCompany:'Describe vision of your company to your followers',
    AboutUpdated:"About updated",
    VisionUpdated:"Vision updated",
    MissionUpdated:"Mission updated",
    AboutNotUpdated:'About not updated',
    VisionNotUpdated:'Vision not updated',
    MissionNotUpdated:'Mission not updated',
    Description:"Description",
    WorkTitle:'Title',
    AddWorkes:'Add workes',
    WorkAdd:'Work add',
    WorkNotAdd:'Work not add',
    WorkRemoved:'Work remove',
    WorkNotRemoved:'Work not remove',
    DeleteWork:"Delete work",
    SureDeleteWork:"Are sure you want to delete this work",
    Public:"Public",
    Private:"Private",
    InformationTechnology:'Information technology',
    OneUpTOFiftyEmploye:'1 - 50 Employe',
    FityUpToHundredEmploye:'50 - 100 Employe',
    HundredUp:'100 - 200 Employe',
    Above200:'Above 200 Employee',
    Bank:'Bank',
    Healthcare:'Health care',
    Retail:'Retail',
    Manufacturing:'Manufacturing',
    Construction:'Construction',
    YourPages:'Pages you follow',
    FollowCompanies:'Follow companies pages to get latest news',
    DeleteConnectionWarnning:'Are sure to remove your connection',
    RemoveConnection:'Remove Connection'
}