export const TranslationAm ={
    Login:'ይግቡ',
    Signup:"ይመዝገቡ",
    ForgetPassword:'የይለፍ ቃል ረስተዋል',
    CreateAccount:'አዲስ መለያ ይፍጠሩ',
    Language:'ቆንቆ',
    Email:'ኢሜይል',
    Password:'የይለፍ ቃል',
    ConfirmPassword:'የይለፍ ቃል ያረጋግጡ',
    FirstName:'የእርሶ ስም',
    LastName:"የአባት ስም",
    Country:"ሀገር",
    City:'ከተማ',
    Phone:'ስልክ',
    OrganizationName:'የድርጅት ስም',
    industry:'ኢንዱስትሪይ',
    OrganizationSize:'የሰራተኝ መጠን',
    OrganizationType:'የድርጅቶ አይነት',
    Tagline:'ስለ ድርጅቶ',
    ResetPassword:'የይለፍ ቃል ያስመልሱ',
    enterEmail:"የኢሜይል አድራሻዎን ያስገቡ",
    Next:'ቀጣይ',
    Back:'ተመለስ',
    VerifyEmail:'የኢሜይል ማረጋገጫ',
    EnterCode:'እባክዎ ወደ ኢሜይልዎ የተላከውን ኮድ ያስገቡ',
    Code:'ኮድ',
    Verify:'አረጋግጥ',
    DidntReceiveCode:"ኮድ አልተቀበለም",
    ResendCode:'ድጋሚ ላክ',
    NewPassword:'አዲስ የይለፍ ቃል',
    PersonalAccount:'የግል ገጽ',
    CompanyPage:'የድርጅት ገጽ',
    Home:"መነሻ ገጽ",
    Message:"መልእክት",
    Network:"ጎደኝች",
    Notification:"አዲስ",
    Profile:"መለያ",
    SettingAndPrivacy:'ቅንብሮች እና ግላዊነት',
    LogOut:"ዘግተው ይውጡ",
    General:'ግላዊነት',
    Security:'ደሕንነት',
    Name:'ስም',
    Location:'መገኛ',
    FNameRequired:'የእርሶ ስም ያስፈልጋል',
    LNameRequired:'የአባት ስም ያስፈልጋል',
    CountryNameRequired:'የሚኖሩብርት ሀገር ስም ያስፈልጋል',
    CityNameRequired:'የሚኖሩበት ከተማ ስም ያስፈልጋል',
    institution:'የተምህርት ተቆም',
    fieldOfStudy:'የተማሩት ትምህርት',
    WorkAt:'የስራ ቦታ',
    Postion:'የስራ ክፍል',
    save:'ቀይር',
    OldPassword:'የይለፍ ቃሎን ያስገቡ',
    ChangePassword:'የይለፍ ቃል ይቀይሩ',
    IncorectOldPassword:'ያስገቡት የ ይለፍ ቃል የተሳሳተ ነው',
    ChangingPasswordFailde:'የይለፍ ቃል መቀየር አልተሳካም',
    PasswordChanged:'የይለፍ ቃል  በተሳካ ሁኔታ ተቀይሮል',
    PleaseEnterOldPassword:'የይለፍ ቃል ማስገባት አለቦት',
    PleaseEnterNewPassword:'አዲስ የይለፍ ቃል ማስገባት አለቦት',
    PleaseConfrimNewPassword:'አዲስ የይለፍ ቃል ማረጋገጫ ማስገባት አለቦት',
    PleaseEnterPassword:'የይለፍ ቃል ማስገባት አልቦት',
    ConfrimPassworNotMatch:'አዲስ የይለፍ ቃል ማረጋገጫ ልክ አይደለም',
    Work:'ስራ',
    DeleteAccount:'መለያ መሰረዝ',
    AccontDeltionFailed:'መለያ መስረዝ አልተሳካም እንደገና ይሞክሩ',
    AgreeToDeleteAccount:'መለያዎን ለመደለት እርግጠኛ ኖት',
    location:'መኖሪያ',
    StudiedAt:'የተማሩበት ተቆም',
    GraduteOf:'የተማሩት ትምህርት',
    startedDate:'ትምህርቱን የጀመሩበት አመት',
    endDate:'ትምህርቱን ያጠናቀቁበት አመት',
    Grade:'የትምህርቶ ውጤት',
    InstitionRequired:'የተማሩበት ተቆም ያስፈልጋል',
    fildeOfStudyRequired:'የተማሩት ትምህርት ያስፈልጋል',
    startedDateRequired:'ትምህርቱን የጀመሩብርት ቀን ያስፈልጋል',
    endDateRequired:'ትምህርቱን ያጠናቀቁበት ቀን ያስፈልጋል',
    GradeRequired:'የትምህርት ውጤቶ  ያስፈልጋል',
    Education:'ትምህርት',
    job:'ስራ'
}
export const TranslationEn ={
    Login:"Login",
    Signup:"Signup",
    ForgetPassword:'Forgot password',
    CreateAccount:'Create Account',
    Language:'Language',
    Email:'Email',
    Password:'Password',
    ConfirmPassword:'Confirm Password',
    FirstName:'First Name',
    LastName:"Last Name",
    Country:"Country",
    City:'City',
    Phone:'Phone Number',
    OrganizationName:'Name',
    industry:'Industry',
    OrganizationSize:'Organization size',
    OrganizationType:'Organization type',
    Tagline:'Tagline',
    ResetPassword:'Reset your password',
    enterEmail:"enter your email address",
    Next:'Next',
    Back:'Back',
    VerifyEmail:'Verify Email',
    EnterCode:'Please enter the code sent to your email',
    Code:'Code',
    Verify:'Verify',
    DidntReceiveCode:"Didn't receive code",
    ResendCode:'Resend Code',
    NewPassword:'New Password',
    PersonalAccount:'Personal Account',
    CompanyPage:'Company Page',
    Home:"Home",
    Message:"Message",
    Network:"My Network",
    Notification:"Notification",
    Profile:"Profile",
    SettingAndPrivacy:'Setting and Perivacy',
    LogOut:"Log Out",
    General:'General',
    Security:'Security',
    Name:'Name',
    Location:'Location',
    FNameRequired:'First Name Requierd',
    LNameRequired:'Last Name Requierd',
    CountryNameRequired:'Country Name is Requierd',
    CityNameRequired:'City Name is Requierd',
    institution:'Institution',
    fieldOfStudy:'Field of Study',
    WorkAt:'Work At',
    Postion:'Postion',
    save:'Save',
    OldPassword:'Old Password',
    ChangePassword:'Change Password',
    IncorectOldPassword:'Incorrect Old Password',
    PasswordChanged:'Password Changed Succfully',
    ChangingPasswordFailde:'Changing Password Failde',
    PleaseEnterOldPassword:'Old password requierd',
    PleaseEnterNewPassword:'New password requierd',
    PleaseConfrimNewPassword:'Confirm password requierd',
    PleaseEnterPassword:'Please Enter Your Password',
    ConfrimPassworNotMatch:'Confrim password does not match',
    Work:'Work',
    DeleteAccount:'Delete Account',
    AccontDeltionFailed:'Account deletion failde try again',
    AgreeToDeleteAccount:'Are you sure to delete your account',
    location:'Lives in',
    StudiedAt:'Studied at',
    GraduteOf:'Gradute of',
    startedDate:'Started year',
    endDate:'End year',
    Grade:'Grade',
    InstitionRequired:'Instition required',
    fildeOfStudyRequired:'Filde of study required',
    startedDateRequired:'started date required',
    endDateRequired:'end date required',
    GradeRequired:'Grade required',
    Education:'Education',
    job:'Job'
}